### ISSUE TITLE
Bug: Port only `<paramref>` descriptions that are found inside the `<TypeParams>` section

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/api-docs-sync#106]
Take this API:

https://github.com/dotnet/runtime/blob/fe1f92e4dc49a396049e8fe0097ed3adefd3dedd/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/Vector64.cs#L91-L99

The comments and signature currently look like this in main:

```cs
        /// <summary>Reinterprets a <see cref="Vector64{T}" /> as a new <see cref="Vector64{U}" />.</summary>
        /// <typeparam name="TFrom">The type of the input vector.</typeparam>
        /// <typeparam name="TTo">The type of the vector <paramref name="vector" /> should be reinterpreted as.</typeparam>
        /// <param name="vector">The vector to reinterpret.</param>
        /// <returns><paramref name="vector" /> reinterpreted as a new <see cref="Vector64{U}" />.</returns>
        /// <exception cref="NotSupportedException">The type of <paramref name="vector" /> (<typeparamref name="TFrom" />) or the type of the target (<typeparamref name="TTo" />) is not supported.</exception>
        [Intrinsic]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Vector64<TTo> As<TFrom, TTo>(this Vector64<TFrom> vector)
```

This is how the intellisense file generates the documentation for the `As` method:

```xml
        <member name="M:System.Runtime.Intrinsics.Vector64.As``2(System.Runtime.Intrinsics.Vector64{``0})">
            <summary>Reinterprets a <see cref="T:System.Runtime.Intrinsics.Vector64`1" /> as a new <see cref="T:System.Runtime.Intrinsics.Vector64`1" />.</summary>
            <typeparam name="TFrom">The type of the input vector.</typeparam>
            <typeparam name="TTo">The type of the vector <paramref name="vector" /> should be reinterpreted as.</typeparam>
            <param name="vector">The vector to reinterpret.</param>
            <returns><paramref name="vector" /> reinterpreted as a new <see cref="T:System.Runtime.Intrinsics.Vector64`1" />.</returns>
            <exception cref="T:System.NotSupportedException">The type of <paramref name="vector" /> (<typeparamref name="TFrom" />) or the type of the target (<typeparamref name="TTo" />) is not supported.</exception>
        </member>
```

The typeparams were recently modified in .NET 7.0. Their names used to be `T` and `U` back in .NET 6.0 RTM, which is what we currently have in the docs xml:

https://github.com/dotnet/dotnet-api-docs/blob/26ce7bb6462d524b6376e81709abc342d73fac15/xml/System.Runtime.Intrinsics/Vector64.xml#L160-L173

```xml
      <TypeParameters>
        <TypeParameter Name="T">
          <Constraints>
            <ParameterAttribute>DefaultConstructorConstraint</ParameterAttribute>
            <ParameterAttribute>NotNullableValueTypeConstraint</ParameterAttribute>
            <BaseTypeName>System.ValueType</BaseTypeName>
          </Constraints>
        </TypeParameter>
        <TypeParameter Name="U">
          <Constraints>
            <ParameterAttribute>DefaultConstructorConstraint</ParameterAttribute>
            <ParameterAttribute>NotNullableValueTypeConstraint</ParameterAttribute>
            <BaseTypeName>System.ValueType</BaseTypeName>
          </Constraints>
        </TypeParameter>
      </TypeParameters>
```

Since dotnet-api-docs in main only has APIs that are shipped, the triple slash of `TFrom` and `TTo` should not be ported automatically, but rather skipped.

Additionally, we need to offer the option (just like we do with normal `<params>`) to get prompted to map the parameters to the correct one.

**Comment by carlossanlop** [comment]
I'm starting to think this is not only a bug on the api-docs-sync side. @gewarren I noticed that in the latest version of `Vector64.xml`, the method `As&lt;T,U&gt;` only indicates `TFrom` and `TTo`, the new names for the typeparams, in the C# `MemberSignature`: https://github.com/dotnet/dotnet-api-docs/blob/26ce7bb6462d524b6376e81709abc342d73fac15/xml/System.Runtime.Intrinsics/Vector64.xml#L141

But in the `<TypeParameters>` section, it's stuck in time with `T` and `U`. Do you think the new names should be indicated somewhere too?

**Comment by gewarren** [comment]
Thanks - I logged https://dev.azure.com/ceapex/Engineering/_workitems/edit/580302.
