### ISSUE TITLE
What is ECMAXml?

### ISSUE THREAD

**Issue by am11** [dotnet/api-docs-sync#108]
From the description of this repo:
> Tool that can port intellisense triple slash comments to ECMAXml files from an api-docs repo. For example: from dotnet/runtime to dotnet-api-docs. 

The only reference I was able to find about ECMAXml format is in this article: https://docs.microsoft.com/en-us/teamblog/announcing-unified-dotnet-experience-on-docs#built-with-open-source-in-mind, which seems to be broken: https://docs.go-mono.com/index.aspx?link=man:mdoc(5).

There is nothing on official website either: https://www.ecma-international.org/?s=ecmaxml

So what is ECMAXml and is there any published spec? :)

**Comment by RussKie** [comment]
@BillWagner @gewarren are you able to help here?

**Comment by carlossanlop** [comment]
@am11 ECMAxml is the xml format we use in api-docs repos to represent documentation for our APIs. Basically, all the xml files you find under here: https://github.com/dotnet/dotnet-api-docs/tree/main/xml

I don't know if we have a published spec. I'm surprised we have a broken link there. Tagging @mairaw in case she also knows what the right target was for that link.

BTW, this repo is the new home of our good ol' DocsPortingTool, which we renamed to api-docs-sync 😃 .

**Comment by gewarren** [comment]
It looks like the correct link is http://docs.go-mono.com/index.aspx?link=man%3amdoc(5). That is a useful spec!

**Comment by am11** [comment]
Thanks! Would `mdoc - Mono Documentation XML Format` be the more accurate term (instead of ECMAXml)? :eyes:

**Comment by carlossanlop** [comment]
Good question. Not sure. This is the first time I hear this "mono documentation format" term to describe the xml spec. And internally, we know is as ECMAxml, AFAIK.

What do you all think?

**Comment by am11** [comment]
Yup, apparently http://docs.go-mono.com/index.aspx?link=man:mdoc(5) is referring to it as "Mono Documentation XML Format". The broken link is perhaps due to expired certificate (HTTP vs. HTTPS)?

Personally (or maybe naively :slightly_smiling_face:), the name `ECMAXml` suggests that spec is published at ecma-international.org, but if there is a different reference (e.g. doc format for ECMA-335 - CIL spec), it makes sense. Maybe, it can be clarified in the repo description?

**Comment by mairaw** [comment]
@joelmartinez perhaps would have more context on this

**Comment by carlossanlop** [comment]
I think ECMAXML is the correct word to use for this repo, since that's how we have always called these xml files. Using `mono...` would be confusing.
