### ISSUE TITLE
Remove `<inheritdoc />` if the tool ported documentation

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/api-docs-sync#116]
Removing it will prevent a CI warning in dotnet-api-docs.

Example: https://github.com/dotnet/dotnet-api-docs/pull/7889#discussion_r837964297

**Comment by gewarren** [comment]
I don't think the problem is that there's full/partial documentation AND an inheritdoc tag. In this case, I don't think there was anything to inherit. I think this issue should be closed as these tags should be looked at on a case-by-case basis.

**Comment by carlossanlop** [comment]
Ah alright. Closing.
