### ISSUE TITLE
Omit the trailing space in self-closing XML tags

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/api-docs-sync#73]
Per https://github.com/dotnet/runtime/pull/48841/files#r585232027, I recommend we change the XML tag generation to omit the trailing space in self-closing tags. That would align with the behavior that VS provides when authoring XML doc comments, even though it's different from what we've done in dotnet-api-docs.

**Comment by gewarren** [comment]
Same as #73?

**Comment by carlossanlop** [comment]
Duplicate of #59
